// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKmg4H7yaizxJK8aWW2wqFGA-iTnT56s',
    appId: '1:660497517730:web:d74577c345707af6c91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    authDomain: 'smokelog-17303.firebaseapp.com',
    storageBucket: 'smokelog-17303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDi4cZWPXDWfSmjIcJdAgU7xRa9sIpbE',
    appId: '1:660497517730:android:69b24f14a7939d26c91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    storageBucket: 'smokelog-17303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7tA65_rkd7G-Kmh_NZAsj3Y5N81YcPHY',
    appId: '1:660497517730:ios:e53ecd3098f2d860c91bfb',
    messagingSenderId: '660497517730',
    authDomain: 'smokelog-17303.firebaseapp.com',
    projectId: 'smokelog-17303',
    storageBucket: 'smokelog-17303.appspot.com',
    iosClientId:
        '660497517730-j7miasb7u60ifg93f3pru8gcm45kg4bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smokeLog2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUKmg4H7yaizxJK8aWW2wqFGA-iTnT56s',
    appId: '1:660497517730:web:601780f35bb39a0ec91bfb',
    messagingSenderId: '660497517730',
    projectId: 'smokelog-17303',
    authDomain: 'smokelog-17303.firebaseapp.com',
    storageBucket: 'smokelog-17303.appspot.com',
  );
}
